HIPS_ORDERS_URL = ENV['SHF_HIPS_URL'] + 'orders/'

HIPS_PRIVATE_KEY = ENV['SHF_HIPS_PRIVATE_KEY']

HIPS_PUBLIC_KEY  = ENV['SHF_HIPS_PUBLIC_KEY']

SHF_MEMBER_FEE   = 40000  # unit == one hundredth of krona
SHF_BRANDING_FEE = 20000
