default: &default
  adapter: postgresql
  encoding: utf8
  collation: sv_SE.UTF-8
  ctype: sv_SE.UTF-8
  template: template0
  host: <%= ENV['DB_HOST'] || ""%>
  username: <%= ENV["DATABASE_POSTGRESQL_USERNAME"] %>
  password: <%= ENV["DATABASE_POSTGRESQL_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shf_project_development

test: &test
  <<: *default
  database: shf_project_test

production:
  <<: *default
  database: shf_project_production
  username: shf_project
  password: <%= ENV['SHF_PROJECT_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
