# Configuration values for SHF (a.k.a. the SHF Project)
#
# This information is loaded in application.rb:
#  module SHFProject
#     class Application < Rails::Application
#       config.x.shf = config_for(:shf)
#     end
#   end
#
#
# The values can be accessed like this:
#  Rails.configuration.x.shf['var'] #=> some value
#
#

default: &default
  google_maps_js_api: "https://maps.googleapis.com/maps/api/js"


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
